### ISSUE TITLE
RuntimeError: Couldn't find acceptable executables for {'clear'}

### ISSUE THREAD

**Issue by alivarastepour** [parsanoori/fastest_protonvpn_server#1]
So I followed the steps in `readme.md` file; then:
```
py main.py
```
and I keep receiving this exception:
```
Traceback (most recent call last):
  File "D:\fastest_protonvpn_server\main.py", line 5, in <module>
    from proton_lib import api
  File "D:\fastest_protonvpn_server\proton_lib\api.py", line 5, in <module>
    from .core.report import BugReport
  File "D:\fastest_protonvpn_server\proton_lib\core\report\__init__.py", line 1, in <module>
    from .bug import BugReport
  File "D:\fastest_protonvpn_server\proton_lib\core\report\bug.py", line 7, in <module>
    from ..subprocess_wrapper import subprocess
  File "D:\fastest_protonvpn_server\proton_lib\core\subprocess_wrapper.py", line 123, in <module>
    subprocess = SubprocessWrapper() # noqa
  File "D:\fastest_protonvpn_server\proton_lib\core\subprocess_wrapper.py", line 34, in __init__
    self.__ensure_executables_exist()
  File "D:\fastest_protonvpn_server\proton_lib\core\subprocess_wrapper.py", line 81, in __ensure_executables_exist
    raise RuntimeError(
RuntimeError: Couldn't find acceptable executables for {'clear'}
```
any thoughts?

**Comment by parsanoori** [comment]
Can you run `clear` on you terminal?

**Comment by alivarastepour** [comment]
nah, cmd.

**Comment by parsanoori** [comment]
try running it there.
Try Googling how to find executable path on windows CMD or Windows Powershell. 
BTW, The libraries were written for Proton-CLI on linux. It may not be able to work on Windows.

**Comment by alivarastepour** [comment]
got it. thx.
